name:                Cosas3D
version:             0.1.0.0
github:              "https://github.com/SamuelCoral/HSAnimations.git"
license:             BSD3
author:              "SamuelCoral"
maintainer:          "samuel.coral.n@gmail.com"
copyright:           "2019 SamuelCoral"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            App category here

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Some 2D/3D experiments written on Haskell using the Gloss library.

dependencies:
- containers
- lens
- gloss
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  Cosas3D-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Cosas3D

tests:
  Cosas3D-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Cosas3D
